rootProject.name = "potatocloud"
include("api")
include("connector")
include("node")
include("core")
include("plugins")
include("plugins:cloudcommand")
include("plugins:hub")
include("plugins:labymod")
include("plugins:notify")
include("plugins:proxy")
include("plugins:utils")
include("platform-plugins")
include("platform-plugins:limbo")
include("platform-plugins:spigot-legacy")
include("platform-plugins:velocity")